### ISSUE TITLE
INSTALL_PAYMENT_AMOUNT is too low

### ISSUE THREAD

**Issue by jekennedy** [casper-network/casper-contracts-js-clients#22]
The INSTALL_PAYMENT_AMOUNT value that is defined in .env.cep47.example is too low to meet the wasm.opcode_costs for Testnet. If a user tries to install the contract, using the default amount specified in .env.cep47.example, they will receive this (confusing) error message:
Error: Contract execution: **Out of gas error**
    at getDeploy (./casper-contracts-js-clients/e2e/utils.ts:38:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async test (./casper-contracts-js-clients/e2e/cep47/install.ts:69:3)

After increasing this amount, the contract was successfully installed. The total CSPR required for this was: 129.38669. Please increase the INSTALL_PAYMENT_AMOUNT with a buffer above this value.

**Comment by andrzej-casper** [comment]
In my case ~150 CSPR was required for `INSTALL_PAYMENT_AMOUNT` - the default value of 115 failed:

![deploy](https://user-images.githubusercontent.com/121791569/216653578-22f8b62f-8fcb-4889-99d8-54378010a222.png)

Same for minting (`MINT_ONE_PAYMENT_AMOUNT`) - the default value of 2 CSPR should be increased to at least 7:
![image](https://user-images.githubusercontent.com/121791569/216654041-8e89794a-4e45-4795-9591-09c75ef8acd1.png)

I stopped here, but it seems that there are more example values that will not work out of the box with current environment. Very annoying :disappointed:.

---

Such issues could be captured with CI/CD :rocket:. I recommend setting up pipeline that runs Casper node and test if deployment + usage are working correctly. I see there is [node image](https://hub.docker.com/r/casperlabs/casper-node-launcher), so it should be rather easy - Docker in Docker FTW!
