### ISSUE TITLE
Installing Erc20 contract is giving error

### ISSUE THREAD

**Issue by Hammad-Mubeen** [casper-network/casper-contracts-js-clients#23]
```
TypeError: Could not serialize 'object': expected 'e', got 'e'.
    at Serializer.convertSingleValue (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:153:31)
    at TypedJSON.toPlainJson (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/parser.ts:463:36)
    at Object.k [as serializer] (/home/hammad/work/casper-contracts-js-clients/node_modules/casper-js-client-helper/node_modules/casper-js-sdk/dist/lib.node.js:1:72434)
    at /home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:245:48
    at Map.forEach (<anonymous>)
    at convertAsObject (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:241:32)
    at Serializer.convertSingleValue (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:166:20)
    at /home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:260:41
    at Map.forEach (<anonymous>)
    at convertAsObject (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:241:32)
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.k [as serializer] (/home/hammad/work/casper-contracts-js-clients/node_modules/casper-js-client-helper/node_modules/casper-js-sdk/dist/lib.node.js:1:72463)
    at /home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:245:48
    at Map.forEach (<anonymous>)
    at convertAsObject (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:241:32)
    at Serializer.convertSingleValue (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:166:20)
    at /home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:260:41
    at Map.forEach (<anonymous>)
    at convertAsObject (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:241:32)
    at Serializer.convertSingleValue (/home/hammad/work/casper-contracts-js-clients/node_modules/typedjson/src/serializer.ts:166:20)
(node:22154) UnhandledPromiseRejectionWarning: Error: Invalid params
    at new JSONRPCError (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/Error.js:24:28)
    at Object.exports.convertJSONToRPCError (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/Error.js:37:16)
    at TransportRequestManager.processResult (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:91:31)
    at TransportRequestManager.resolveRes (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:113:18)
    at TransportRequestManager.resolveResponse (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:53:25)
    at HTTPTransport.<anonymous> (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:107:68)
    at step (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:46:23)
    at Object.next (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:27:53)
    at fulfilled (/home/hammad/work/casper-contracts-js-clients/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:18:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/72869611/177585498-e7bc5db6-8384-42b6-b9a7-1f520bf1c62d.png)
![image](https://user-images.githubusercontent.com/72869611/177585579-e01b2d39-8876-4f88-b4ba-c6bd7e4dc019.png)

**Comment by RitaMAllenCA** [comment]
@zoltans - please review and see if this OLD ticket is still an issue

**Comment by RitaMAllenCA** [comment]
won't do unless reporter responds.
