### ISSUE TITLE
ERC20 Transfer function returns "Invalid Param"

### ISSUE THREAD

**Issue by davidtai** [casper-network/casper-contracts-js-clients#27]
Calling with a publicKey hex
```
const deployHash = await erc20.transfer(
  KEYS, // Key pair used for signing
  receiverPublicKey, // Receiver public key
  "2000000000", // Amount to transfer
  "10000000000000" // Payment amount
);
```

Like
```
const deployHash = await erc20.transfer(
      keys,
      CLPublicKey.fromHex(account),
      amount.toString(),
      '10000000000',
)
```

Returns
```
/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/Error.js:24
        var _this = _super.call(this, message) || this;
                           ^
JSONRPCError: Invalid params
    at new JSONRPCError (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/Error.js:24:28)
    at Object.exports.convertJSONToRPCError (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/Error.js:37:16)
    at TransportRequestManager.processResult (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:91:31)
    at TransportRequestManager.resolveRes (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:113:18)
    at TransportRequestManager.resolveResponse (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/TransportRequestManager.js:53:25)
    at HTTPTransport.<anonymous> (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:112:68)
    at step (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:46:23)
    at Object.next (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:27:53)
    at fulfilled (/mnt/b/projects/uniswap-scripts/node_modules/@open-rpc/client-js/build/transports/HTTPTransport.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: -32602,
  data: null
}
```

Manual Casper Client calls with the same account information work fine.  It seems like there's probably an issue with how the public key is being sent.

**Comment by RitaMAllenCA** [comment]
@hoffmannjan please triage so we can discuss this at standup, thank you
